server:
  port: 8000

app:
  ia:
    atarax:
      services:
        provincia:
          endpoint: http://localhost:8100/
          type: remote # in-memory, remote
        localidad:
          endpoint: http://localhost:8200/
          type: remote # in-memory, remote

spring:
  application:
    name: web
  cloud:
    config:
      enabled: true
      uri: http://localhost:8300
      user: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8400

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/

# circuit-breaker
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 10s
      cancelRunningFuture: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
