server:
  port: 8100

spring:
  application:
    name: provincias
  jpa:
    hibernate:
      ddl-auto: update
#      show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/localizaciones
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/