INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (1, 'VI', 'Álava');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (2, 'AB', 'Albacete');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (3, 'A', 'Alicante');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (4, 'AL', 'Almería');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (5, 'AV', 'Ávila');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (6, 'BA', 'Badajoz');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (7, 'PM', 'Baleares');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (8, 'B', 'Barcelona');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (9, 'BU', 'Burgos');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (10, 'CC', 'Cáceres');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (11, 'CA', 'Cádiz');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (12, 'CS', 'Castellón');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (13, 'CR', 'Ciudad Real');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (14, 'CO', 'Córdoba');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (15, 'C', 'La Coruña');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (16, 'CU', 'Cuenca');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (17, 'GI', 'Gerona');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (18, 'GR', 'Granada');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (19, 'GU', 'Guadalajara');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (20, 'SS', 'Guipúzcoa');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (21, 'H', 'Huelva');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (22, 'HU', 'Huesca');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (23, 'J', 'Jaén');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (24, 'LE', 'León');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (25, 'L', 'Lérida');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (26, 'LO', 'La Rioja');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (27, 'LU', 'Lugo');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (28, 'M', 'Madrid');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (29, 'MA', 'Málaga');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (30, 'MU', 'Murcia');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (31, 'NA', 'Navarra');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (32, 'OU', 'Orense');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (33, 'O', 'Asturias');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (34, 'P', 'Palencia');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (35, 'GC', 'Las Palmas');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (36, 'PO', 'Pontevedra');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (37, 'SA', 'Salamanca');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (38, 'TF', 'Santa Cruz de Tenerife');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (39, 'S', 'Cantabria');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (40, 'SG', 'Segovia');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (41, 'SE', 'Sevilla');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (42, 'SO', 'Soria');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (43, 'T', 'Tarragona');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (44, 'TE', 'Teruel');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (45, 'TO', 'Toledo');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (46, 'V', 'Valencia');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (47, 'VA', 'Valladolid');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (48, 'BI', 'Vizcaya');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (49, 'ZA', 'Zamora');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (50, 'Z', 'Zaragoza');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (51, 'CE', 'Ceuta');
INSERT IGNORE INTO localizaciones.provincia (id, cod, nombre) VALUES (52, 'ML', 'Melilla');