server:
  port: 8600

spring:
  application:
    name: configuracion
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atarax-ia/Microservicios.git
          skip-ssl-validation: true
          default-label: main
          searchPaths: config_files
          clone-on-start: true
