server:
  port: 8300

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///${user.dir}/config_data
  security:
    user:
      name: root
      password: s3cr3t
  application:
    name: configuracion