server:
  port: 8600

spring:
  application:
    name: configuracion
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atarax-ia/Microservicios/tree/main/Configuracion/configuracion/config_files
          clone-on-start: true
