spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: web
          uri: lb://web
          predicates:
            - Path=/v1/api/**
        - id: localidades
          uri: lb://localidades
          predicates:
           - Path=/v1/api/localidades/**
        - id: provincias
          uri: lb://provincias
          predicates:
           - Path=/v1/api/provincias/**
    config:
      uri: http://localhost:8600
#  boot:
#    admin:
#      client:
#        url: http://localhost:8400

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"