server:
  port: 8200

spring:
  application:
    name: localidades
  jpa:
    hibernate:
      ddl-auto: update
#      show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/localizaciones
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      enabled: true
      uri: http://localhost:8300
      user: root
      password: s3cr3t

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/